# Generated by Django 4.1.7 on 2023-04-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('Estrela', 'ESTRELA'), ('Galáxia', 'GALÁXIA'), ('Planeta', 'PLANETA')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
